### ISSUE TITLE
[Protection] SoftAnchor 

### ISSUE THREAD

**Issue by Flashfire42** [mnadareski/BurnOutSharp#205] opened 2022-12-15 22:08 UTC
https://store.steampowered.com/news/posts/?feed=kotaku&appids=34019&appgroupname=Alpha+Protocol&enddate=1273766399
https://www.pcgamingwiki.com/wiki/Alpha_Protocol

**Comment by TheRogueArchivist** [comment] 2022-12-24 06:38
Duplicate of #85.

**Closed by TheRogueArchivist** 2022-12-24 06:38 UTC
