### ISSUE TITLE
[Bug?] Weird magical mysterious crashes during scanning

### ISSUE THREAD

**Issue by NovaSAurora** [mnadareski/BurnOutSharp#54] opened 2021-08-14 22:48 UTC
https://media.discordapp.net/attachments/461797735427735562/876235551248904243/unknown.png

Hell if I know what's going on

**Comment by mnadareski** [comment] 2021-09-15 03:20
@NovaSAurora have you run into this error at all on the same discs? A lot has changed this past month.

**Comment by mnadareski** [comment] 2022-03-14 16:59
Can't reproduce, closing.

**Closed by mnadareski** 2022-03-14 16:59 UTC
Labels: bug, question
