### ISSUE TITLE
[Protection] Microsoft Playfab

### ISSUE THREAD

**Issue by Flashfire42** [mnadareski/BurnOutSharp#202] opened 2022-12-15 07:43 UTC
https://store.steampowered.com/app/1428140/Riding_Seas/
Incorporates 3rd-party DRM: Microsoft Playfab

**Comment by Zopolis4** [comment] 2022-12-15 11:49
A variety of games are listed [here](https://azure.microsoft.com/en-us/products/playfab/#overview) as well under `Games that run on PlayFab`.

**Comment by TheRogueArchivist** [comment] 2022-12-24 05:43
Duplicate of #200.

**Closed by TheRogueArchivist** 2022-12-24 05:43 UTC
